apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: service-catalog
  name: service-catalog
spec:
  replicas: 2  # Adjust the number of replicas as needed
  selector:
    matchLabels:
      app.kubernetes.io/name: service-catalog
  template:
    metadata:
      labels:
        app.kubernetes.io/name: service-catalog
    spec:
      containers:
      - image: service-catalog:latest
        name: service-catalog
        imagePullPolicy: Never
        ports:
        - containerPort: 3000  # Assuming your service runs on port 3000